# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# sudo bundle install
# sudo bundle exec jekyll serve
title: Shenyang Shi
email: shenyang.shih@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shenyangshi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima
remote_theme: hydecorp/hydejack@v9
plugins:
  - jekyll-feed
  - jekyll-remote-theme
markdown: kramdown

author:
  name: Shenyang Shi
  bio: "PhD student in the Department of Physics at Columbia University"
  home: "New York, NY"
  email: "ss6109@columbia.edu"
  social:
    email: ss6109@columbia.edu
    github:  shenyangshi
    google-scholar: https://scholar.google.com/citations?user=NV8YSoYAAAAJ&hl=en


# Design of the pages
accent_image: /assets/img/main_page.jpeg
menu:
  - title: About
    url: /
  - title: Blog
    url:   /blog/
  - title: Travel
    url:   /travel/
  - title: Photography
    url:   /photography/
google_analytics: G-D1LTJMVZK9
collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true


# Comment section
#disqus: shenyangshi
#defaults:
#  - scope:
#      type: blog, travel, photography
#    values:
#      comments: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
